=== choutkamartin/html-css-xml-xsd-xsl/xml-html/data.xsd
<?xml version="1.0"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:attribute name="znacka">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="Kingston" />
                <xs:enumeration value="Gigabyte" />
                <xs:enumeration value="Cooler Master" />
                <xs:enumeration value="Noctua" />
                <xs:enumeration value="Realtek" />
                <xs:enumeration value="Verbatim" />
                <xs:enumeration value="PremiumCord" />
                <xs:enumeration value="Intel" />
                <xs:enumeration value="Elgato" />
                <xs:enumeration value="Nvidia" />
                <xs:enumeration value="Western Digital" />
                <xs:enumeration value="AMD" />
            </xs:restriction>
        </xs:simpleType>
    </xs:attribute>

    <xs:attribute name="kapacita">
        <xs:simpleType>
            <xs:restriction base="xs:integer">
                <xs:pattern value="[1-9][0-9]*" />
            </xs:restriction>
        </xs:simpleType>
    </xs:attribute>

    <xs:attribute name="mena">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="CZK" />
                <xs:enumeration value="EUR" />
                <xs:enumeration value="USD" />
            </xs:restriction>
        </xs:simpleType>
    </xs:attribute>

    <xs:attribute name="socket">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="Intel 1150" />
                <xs:enumeration value="AMD AM4" />
                <xs:enumeration value="AMD SP3" />
                <xs:enumeration value="AMD TR4" />
                <xs:enumeration value="AMD TRX4" />
                <xs:enumeration value="AMD WRX8 4094" />
                <xs:enumeration value="Intel 1151" />
                <xs:enumeration value="Intel 1156" />
                <xs:enumeration value="Intel 1200" />
                <xs:enumeration value="Intel 2011-3" />
                <xs:enumeration value="Intel 2066" />
                <xs:enumeration value="Intel 3647" />
            </xs:restriction>
        </xs:simpleType>
    </xs:attribute>

    <xs:attribute name="format">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="ATX" />
                <xs:enumeration value="mATX" />
                <xs:enumeration value="mITX" />
                <xs:enumeration value="eATX" />
                <xs:enumeration value="mDTX" />
                <xs:enumeration value="uATX" />
                <xs:enumeration value="XL-ATX" />
            </xs:restriction>
        </xs:simpleType>
    </xs:attribute>

    <xs:element name="root">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="pocitace">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="pocitac" maxOccurs="unbounded" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:positiveInteger" name="id" />
                                        <xs:element name="komponenty">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="procesor" minOccurs="1">
                                                        <xs:complexType>
                                                            <xs:simpleContent>
                                                                <xs:extension base="xs:string">
                                                                    <xs:attribute ref="znacka" />
                                                                    <xs:attribute ref="socket" />
                                                                </xs:extension>
                                                            </xs:simpleContent>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element name="grafickaKarta" minOccurs="1">
                                                        <xs:complexType>
                                                            <xs:simpleContent>
                                                                <xs:extension base="xs:string">
                                                                    <xs:attribute ref="znacka" />
                                                                    <xs:attribute ref="kapacita" />
                                                                </xs:extension>
                                                            </xs:simpleContent>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element name="disky">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="disk" maxOccurs="4" minOccurs="1">
                                                                    <xs:complexType>
                                                                        <xs:simpleContent>
                                                                            <xs:extension base="xs:string">
                                                                                <xs:attribute ref="znacka" />
                                                                                <xs:attribute ref="kapacita" />
                                                                            </xs:extension>
                                                                        </xs:simpleContent>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element name="pameti">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="pamet" maxOccurs="4" minOccurs="1">
                                                                    <xs:complexType>
                                                                        <xs:simpleContent>
                                                                            <xs:extension base="xs:string">
                                                                                <xs:attribute ref="znacka" />
                                                                            </xs:extension>
                                                                        </xs:simpleContent>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element name="zakladniDeska">
                                                        <xs:complexType>
                                                            <xs:simpleContent>
                                                                <xs:extension base="xs:string">
                                                                    <xs:attribute ref="znacka" />
                                                                    <xs:attribute ref="format" />
                                                                </xs:extension>
                                                            </xs:simpleContent>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element name="skrin" minOccurs="1">
                                                        <xs:complexType>
                                                            <xs:simpleContent>
                                                                <xs:extension base="xs:string">
                                                                    <xs:attribute ref="znacka" />
                                                                    <xs:attribute type="xs:positiveInteger" name="delka" use="required" />
                                                                    <xs:attribute type="xs:positiveInteger" name="sirka" use="required" />
                                                                </xs:extension>
                                                            </xs:simpleContent>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element name="zdroj" minOccurs="1">
                                                        <xs:complexType>
                                                            <xs:simpleContent>
                                                                <xs:extension base="xs:string">
                                                                    <xs:attribute ref="znacka" />
                                                                    <xs:attribute type="xs:positiveInteger" name="prikon" use="required" />
                                                                </xs:extension>
                                                            </xs:simpleContent>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element name="chlazeni">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="chladic" minOccurs="1">
                                                                    <xs:complexType>
                                                                        <xs:simpleContent>
                                                                            <xs:extension base="xs:string">
                                                                                <xs:attribute ref="znacka" />
                                                                            </xs:extension>
                                                                        </xs:simpleContent>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                                <xs:element name="ventilatory">
                                                                    <xs:complexType>
                                                                        <xs:sequence>
                                                                            <xs:element name="ventilator">
                                                                                <xs:complexType>
                                                                                    <xs:simpleContent>
                                                                                        <xs:extension base="xs:string">
                                                                                            <xs:attribute ref="znacka" />
                                                                                        </xs:extension>
                                                                                    </xs:simpleContent>
                                                                                </xs:complexType>
                                                                            </xs:element>
                                                                        </xs:sequence>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element name="optickaMechanika">
                                                        <xs:complexType>
                                                            <xs:simpleContent>
                                                                <xs:extension base="xs:string">
                                                                    <xs:attribute ref="znacka" />
                                                                </xs:extension>
                                                            </xs:simpleContent>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element name="televizniKarta">
                                                        <xs:complexType>
                                                            <xs:simpleContent>
                                                                <xs:extension base="xs:string">
                                                                    <xs:attribute ref="znacka" />
                                                                </xs:extension>
                                                            </xs:simpleContent>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element name="sitovaKarta">
                                                        <xs:complexType>
                                                            <xs:simpleContent>
                                                                <xs:extension base="xs:string">
                                                                    <xs:attribute ref="znacka" />
                                                                </xs:extension>
                                                            </xs:simpleContent>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element name="zaznamoveZarizeni">
                                                        <xs:complexType>
                                                            <xs:simpleContent>
                                                                <xs:extension base="xs:string">
                                                                    <xs:attribute ref="znacka" />
                                                                </xs:extension>
                                                            </xs:simpleContent>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element name="kabely">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="kabel" maxOccurs="unbounded" minOccurs="0">
                                                                    <xs:complexType>
                                                                        <xs:simpleContent>
                                                                            <xs:extension base="xs:string">
                                                                                <xs:attribute ref="znacka" />
                                                                            </xs:extension>
                                                                        </xs:simpleContent>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="cena">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:extension base="xs:positiveInteger">
                                                        <xs:attribute ref="mena" />
                                                    </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== choutkamartin/html-css-xml-xsd-xsl/xml-html/data.xml
<?xml version="1.0"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="data.xsd">
    <pocitace>
        <pocitac>
            <id>1</id>
            <komponenty>
                <procesor znacka="Intel" socket="Intel 1150">Core i5 2000</procesor>
                <grafickaKarta znacka="Nvidia" kapacita="4">GeForce RTX 2080</grafickaKarta>
                <disky>
                    <disk znacka="Western Digital" kapacita="4">Red</disk>
                    <disk znacka="Western Digital" kapacita="4">Red</disk>
                </disky>
                <pameti>
                    <pamet znacka="Kingston">DDR3 4GB</pamet>
                    <pamet znacka="Kingston">DDR3 4GB</pamet>
                </pameti>
                <zakladniDeska znacka="Gigabyte" format="ATX">Phantom</zakladniDeska>
                <skrin znacka="Cooler Master" delka="250" sirka="50">Nikaragua</skrin>
                <zdroj znacka="Cooler Master" prikon="400">Green Power</zdroj>
                <chlazeni>
                    <chladic znacka="Noctua">MegaCooler 3</chladic>
                    <ventilatory>
                        <ventilator znacka="Noctua">MegaFan 3</ventilator>
                    </ventilatory>
                </chlazeni>
                <optickaMechanika znacka="Verbatim">
                        CD/RW Optic
                        </optickaMechanika>
                <televizniKarta znacka="Realtek">TV 3</televizniKarta>
                <sitovaKarta znacka="Intel">Ethernet 1000GB</sitovaKarta>
                <zaznamoveZarizeni znacka="Elgato">Stream Deck</zaznamoveZarizeni>
                <kabely>
                    <kabel znacka="PremiumCord">230V</kabel>
                </kabely>
            </komponenty>
            <cena mena="CZK">20000</cena>
        </pocitac>
        <pocitac>
            <id>4</id>
            <komponenty>
                <procesor znacka="AMD" socket="Intel 1150">AMD Phenom II X3</procesor>
                <grafickaKarta znacka="Nvidia" kapacita="4">GeForce RTX 3060</grafickaKarta>
                <disky>
                    <disk znacka="Western Digital" kapacita="2">Red</disk>
                    <disk znacka="Western Digital" kapacita="2">Red</disk>
                </disky>
                <pameti>
                    <pamet znacka="Kingston">DDR4 4GB</pamet>
                    <pamet znacka="Kingston">DDR4 4GB</pamet>
                </pameti>
                <zakladniDeska znacka="Gigabyte" format="ATX">Bulldog</zakladniDeska>
                <skrin znacka="Cooler Master" delka="250" sirka="50">Nikaragua</skrin>
                <zdroj znacka="Cooler Master" prikon="400">Green Power</zdroj>
                <chlazeni>
                    <chladic znacka="Noctua">MegaCooler 3</chladic>
                    <ventilatory>
                        <ventilator znacka="Noctua">CoolFan 5</ventilator>
                    </ventilatory>
                </chlazeni>
                <optickaMechanika />
                <televizniKarta znacka="Realtek">TV 3</televizniKarta>
                <sitovaKarta znacka="Intel">Ethernet 2</sitovaKarta>
                <zaznamoveZarizeni znacka="Elgato">Stream Deck</zaznamoveZarizeni>
                <kabely>
                    <kabel znacka="PremiumCord">230V</kabel>
                </kabely>
            </komponenty>
            <cena mena="CZK">13000</cena>
        </pocitac>
        <pocitac>
            <id>5</id>
            <komponenty>
                <procesor znacka="Intel" socket="Intel 1150">Core i5 2000</procesor>
                <grafickaKarta znacka="Nvidia" kapacita="4">GeForce RTX 1050 Ti</grafickaKarta>
                <disky>
                    <disk znacka="Western Digital" kapacita="4">Red</disk>
                    <disk znacka="Western Digital" kapacita="1">Green</disk>
                </disky>
                <pameti>
                    <pamet znacka="Kingston">DDR4 8GB</pamet>
                    <pamet znacka="Kingston">DDR4 8GB</pamet>
                </pameti>
                <zakladniDeska znacka="Gigabyte" format="ATX">Phantom</zakladniDeska>
                <skrin znacka="Cooler Master" delka="250" sirka="50">MasterBox</skrin>
                <zdroj znacka="Cooler Master" prikon="400">Green Power</zdroj>
                <chlazeni>
                    <chladic znacka="Noctua">MegaCooler 3</chladic>
                    <ventilatory>
                        <ventilator znacka="Noctua">FanMaster 2</ventilator>
                    </ventilatory>
                </chlazeni>
                <optickaMechanika znacka="Verbatim">
                        CD/RW Optic
                        </optickaMechanika>
                <televizniKarta />
                <sitovaKarta />
                <zaznamoveZarizeni />
                <kabely>
                    <kabel znacka="PremiumCord">230V</kabel>
                </kabely>
            </komponenty>
            <cena mena="CZK">20000</cena>
        </pocitac>
        <pocitac>
            <id>2</id>
            <komponenty>
                <procesor znacka="Intel" socket="AMD AM4">Ryzen 12 6000</procesor>
                <grafickaKarta znacka="AMD" kapacita="4">Radeon HD 5770</grafickaKarta>
                <disky>
                    <disk znacka="Western Digital" kapacita="4">Red 1000GB</disk>
                    <disk znacka="Western Digital" kapacita="4">SSDFX 128GB</disk>
                </disky>
                <pameti>
                    <pamet znacka="Kingston">DDR4 8GB</pamet>
                </pameti>
                <zakladniDeska znacka="Gigabyte" format="ATX">Knight</zakladniDeska>
                <skrin znacka="Cooler Master" delka="250" sirka="50">MasterCase</skrin>
                <zdroj znacka="Cooler Master" prikon="400">Green Power</zdroj>
                <chlazeni>
                    <chladic znacka="Noctua">MegaCooler 3</chladic>
                    <ventilatory>
                        <ventilator znacka="Noctua">FanMaster 3</ventilator>
                    </ventilatory>
                </chlazeni>
                <optickaMechanika znacka="Verbatim">
                        CD/RW Optic
                        </optickaMechanika>
                <televizniKarta znacka="Realtek">TV 3</televizniKarta>
                <sitovaKarta znacka="Intel">Ethernet 4</sitovaKarta>
                <zaznamoveZarizeni znacka="Elgato">Stream Deck</zaznamoveZarizeni>
                <kabely>
                    <kabel znacka="PremiumCord">230V</kabel>
                </kabely>
            </komponenty>
            <cena mena="CZK">26000</cena>
        </pocitac>
        <pocitac>
            <id>8</id>
            <komponenty>
                <procesor znacka="Intel" socket="Intel 1150">Core i5 2000</procesor>
                <grafickaKarta znacka="AMD" kapacita="4">GeForce RTX 2080</grafickaKarta>
                <disky>
                    <disk znacka="Western Digital" kapacita="4">Black</disk>
                </disky>
                <pameti>
                    <pamet znacka="Kingston">DDR3 4GB</pamet>
                    <pamet znacka="Kingston">DDR3 4GB</pamet>
                </pameti>
                <zakladniDeska znacka="Gigabyte" format="ATX">Warrior</zakladniDeska>
                <skrin znacka="Cooler Master" delka="250" sirka="50">MasterBox</skrin>
                <zdroj znacka="Cooler Master" prikon="400">Red Power</zdroj>
                <chlazeni>
                    <chladic znacka="Noctua">Arctic Bear</chladic>
                    <ventilatory>
                        <ventilator znacka="Noctua">Arctic Freeze</ventilator>
                    </ventilatory>
                </chlazeni>
                <optickaMechanika znacka="Verbatim">
                        CD/RW Optic
                        </optickaMechanika>
                <televizniKarta znacka="Realtek">TV 3</televizniKarta>
                <sitovaKarta znacka="Intel">Ethernet 4</sitovaKarta>
                <zaznamoveZarizeni znacka="Elgato">Stream Deck</zaznamoveZarizeni>
                <kabely>
                    <kabel znacka="PremiumCord">230V</kabel>
                </kabely>
            </komponenty>
            <cena mena="EUR">2000</cena>
        </pocitac>
        <pocitac>
            <id>15</id>
            <komponenty>
                <procesor znacka="Intel" socket="Intel 1150">Core i5 2000</procesor>
                <grafickaKarta znacka="AMD" kapacita="4">Radeon RX 6800 XT</grafickaKarta>
                <disky>
                    <disk znacka="Western Digital" kapacita="1">Blue</disk>
                    <disk znacka="Western Digital" kapacita="1">Red</disk>
                </disky>
                <pameti>
                    <pamet znacka="Kingston">DDR3 4GB</pamet>
                    <pamet znacka="Kingston">DDR3 4GB</pamet>
                </pameti>
                <zakladniDeska znacka="Gigabyte" format="ATX">Phantom</zakladniDeska>
                <skrin znacka="Cooler Master" delka="250" sirka="50">Elite 342</skrin>
                <zdroj znacka="Cooler Master" prikon="750">MWE Gold 750</zdroj>
                <chlazeni>
                    <chladic znacka="Noctua">MegaCooler 3</chladic>
                    <ventilatory>
                        <ventilator znacka="Noctua">Thunder 1000</ventilator>
                    </ventilatory>
                </chlazeni>
                <optickaMechanika znacka="Verbatim">
                        CD/RW Optic
                        </optickaMechanika>
                <televizniKarta znacka="Realtek">TV 8</televizniKarta>
                <sitovaKarta znacka="Intel">Ethernet 4</sitovaKarta>
                <zaznamoveZarizeni znacka="Elgato">Record Deck</zaznamoveZarizeni>
                <kabely>
                    <kabel znacka="PremiumCord">230V</kabel>
                </kabely>
            </komponenty>
            <cena mena="CZK">46000</cena>
        </pocitac>
        <pocitac>
